### ISSUE TITLE
problem when building a project with clang

### ISSUE THREAD

**Issue by sereyv280699** [llvm-fortran/fort#20]
Hello.
I had a problem building a project with clang.
Namely, I get similar output:

/root/llvm-6.0.0.src/tools/fort-6.0/lib/CodeGen/CGBuilder.h:20:25: error:
       template argument must be type
typedef llvm :: IRBuilder <false> CGBuilderTy;
                         ^ ~~~~
/root/llvm-6.0.0.src/include/llvm/IR/IRBuilder.h:666:20: note: template
       parameter is declared here
template <typename T = ConstantFolder,
                    ^

**Comment by ppenzin** [comment]
Hi, thank you for asking. What system are you building on and which version of Clang are you using?

**Comment by sereyv280699** [comment]
i am use alpine linux with clang 6.0

**Comment by ppenzin** [comment]
You build is hitting "#ifdef NDEBUG" case, which LLVM tries to [avoid](https://github.com/llvm-mirror/llvm/blob/release_60/cmake/modules/HandleLLVMOptions.cmake#L64). Typedef is inconsistent with the LLVM header, this needs to be fixed (non-NDEBUG code is correct).

**Comment by ppenzin** [comment]
@sereyv280699, please try release `6.0.1` or get the latest code from `release_60` branch
